# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            hlúposti
tagline:          verejný denníček plný hlúpostí
url:              http://hlupsti.github.io

paginate:         5
