# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            hlúposti
tagline:          …a občas možno niečo viac
url:              http://hlupsti.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
