# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            hlúposti
tagline:          "minimum obrázkov, maximum hlúpostí"
url:              http://hlupsti.github.io

paginate:         5
